# Generated by Django 3.2.13 on 2022-10-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quesion',
            new_name='Question',
        ),
    ]
