# Generated by Django 4.1.5 on 2023-02-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
    ]
