# Generated by Django 4.1.5 on 2023-01-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('time', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('perfect', models.IntegerField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
            ],
        ),
    ]
