# Generated by Django 3.2.7 on 2022-10-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221013_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='movies.Hashtag'),
        ),
    ]
